### ISSUE TITLE
1.15.2 version broken

### ISSUE THREAD

**Issue by brisingraerowing** [puggan/decimalCoins#1]
When I try launching the game with Forge 31.2.30+, I get an error stating that this mod needs the 'javafml:32' language provider.

**Comment by puggan** [comment]
Tried to reproducing it by running the versions:
* MC: 1.15.2
* Forge 31.2.30
* decimalCoin: 1.1.1

![2020-08-30_01 17 01](https://user-images.githubusercontent.com/866668/91649032-68dffa80-ea6f-11ea-8be8-731b751223ad.png)

But on my computer that combination of version works fine.

**Comment by puggan** [comment]
A, seems to be some problem when the jar for 1.1.0 was created,
please try the 1.1.1 version.
https://www.curseforge.com/minecraft/mc-mods/decimal-coins/files/3045470
