### ISSUE TITLE
Reduce max stack count from 100 to 64

### ISSUE THREAD

**Issue by Bawbby** [puggan/decimalCoins#3]
Minecraft seems to only handle item stacks of 64 or less properly. Going above that causes issues.

I'm on Minecraft 1.16 with Fabric.

**Comment by puggan** [comment]
To keep it decimal, and avoid the 65+ problems, I redused it down to 50.
Now avaible in v1.3.0 on Fabric 1.16 and 1.17, and Forge 1.14, 1.15, and 1.16.
